<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

# Pythonic Method

In [14]:

X = [[1,3,4],
     [2,5,7],
     [5,9,6]]

Y=  [[1,0,0],
    [0,1,0],
    [0,0,1]]

Z = [[1,2,3,4,5,6],
     [7,8,9,10,11,12]]

In [15]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists

def MulMatrix(a, b):
    if len(a[0]) != len(b):
        return print("Multiplication not possible")
        
    # Create the result matrix and fill it with zeros
    result=[]
    
    temp_row=len(b[0])*[0]
    for r in range(len(a)):
        result.append(temp_row[:])
    for row_index in range(len(a)):
        for col_index in range(len(b[0])):
            sum=0
            for k in range(len(a[0])):
                sum=sum+a[row_index][k]*b[k][col_index]
            result[row_index][col_index]=sum
    return result

print(MulMatrix(X, Y))        

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]


# Numpy Method

In [16]:
import numpy as np

# X (3X3) & Y (3X4) can be multiplied
print(np.dot(X,Y))

# Y (3X4) & Z (2X6) cannot be multiplied  
print(np.dot(Y,Z))

[[1 3 4]
 [2 5 7]
 [5 9 6]]


ValueError: shapes (3,3) and (2,6) not aligned: 3 (dim 1) != 2 (dim 0)

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [8]:
import random
from itertools import accumulate
from bisect import bisect

A = [0,5,27,6,13,28,100,45,10,79]

def propotional_sampling(A,n=100):
    sum=0
    for i in range(len(A)):
        sum = sum + A[i]
    
    d_dash=[]
    
    for j in range(len(A)):
        d_dash.append((A[j]/sum))
    
    #cumulative sum

    d_bar = [*accumulate(d_dash)]
    out = []
    for _ in range(n):
        i = random.uniform(0.0,1.0)                     
        idx = bisect(d_bar, i)    
        out.append(A[idx])
    
    return out

propotional_sampling(A)

[45,
 100,
 45,
 79,
 27,
 100,
 45,
 28,
 79,
 28,
 28,
 79,
 45,
 100,
 5,
 100,
 28,
 100,
 100,
 100,
 27,
 79,
 100,
 10,
 100,
 79,
 27,
 79,
 100,
 45,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 79,
 100,
 100,
 79,
 100,
 27,
 100,
 100,
 100,
 28,
 100,
 6,
 5,
 100,
 100,
 100,
 100,
 79,
 45,
 100,
 10,
 79,
 45,
 79,
 45,
 45,
 45,
 13,
 45,
 100,
 79,
 45,
 100,
 10,
 100,
 45,
 100,
 5,
 79,
 79,
 100,
 45,
 100,
 100,
 100,
 100,
 79,
 79,
 100,
 79,
 45,
 5,
 28,
 45,
 100,
 27,
 100,
 28,
 28,
 100,
 13,
 79,
 79]

<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [17]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    String = re.sub("[^0-9]","",str(String))
    String = re.sub('\d','#',String)
    return String # modified string which is after replacing the # with digits

print(replace_digits('a2b3c4'))
print(replace_digits('234'))
print(replace_digits('#2a$#b%c%561#'))
print(replace_digits('abc'))

###
###
####



Reference :
https://stackoverflow.com/questions/19084443/replacing-digits-with-str-replace
https://stackoverflow.com/questions/961632/converting-integer-to-string
https://stackoverflow.com/questions/1249388/removing-all-non-numeric-characters-from-string-in-python

<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [5]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
# you can free to change all these codes/structure
def display_dash_board(students, marks):
    dictionary = dict(zip(Students,Marks))
    print('top_5_students')
    for key, value in sorted(dictionary.items(), key=lambda item: item[1],reverse=True)[:5]:
          print("%s: %s" % (key, value))
    print('\nleast_5_students')
    for key, value in sorted(dictionary.items(), key=lambda item: item[1])[:5]:
          print("%s: %s" % (key, value))
        
    #students_within_25_and_75 = # compute this
    print('\nstudents_within_25_and_75')
    for key, value in sorted(dictionary.items(), key=lambda item: item[1]):
      percentage = value * 100.0 / 100  # I assumed 100 as total marks 
      if 25 < percentage < 75 :
            print("%s: %s" % (key, value))

display_dash_board(Students, Marks)


top_5_students
student8: 98
student10: 80
student2: 78
student5: 48
student7: 47

least_5_students
student3: 12
student4: 14
student9: 35
student6: 43
student1: 45

students_within_25_and_75
student9: 35
student6: 43
student1: 45
student7: 47
student5: 48


Reference :
https://stackoverflow.com/questions/209840/convert-two-lists-into-a-dictionary
https://www.saltycrane.com/blog/2007/09/how-to-sort-python-dictionary-by-keys/
https://stackoverflow.com/questions/16772071/sort-dict-by-value-python

<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [6]:
import math


S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]

P= (3,-4)

dist = []

def closest_points_to_p(S, P):
  
  for i in range(len(S)):
    
    d = math.acos(((S[i][0]*P[0])+(S[i][1]*P[1]))/((math.sqrt((S[i][0]**2)+(S[i][1]**2))) *(math.sqrt((P[0]**2)+(P[1]**2)))))

    dist.append(d)

closest_points_to_p(S, P)

dictionary = dict(zip(S,dist))

for key, value in sorted(dictionary.items(), key=lambda item: item[1])[:5]:
  print("%s: %s" % (key, value))


(6, -7): 0.06512516333438509
(1, -1): 0.14189705460416438
(6, 0): 0.9272952180016123
(-5, -8): 1.2021004241368467
(-1, -1): 1.4288992721907328


Reference: 
https://stackoverflow.com/questions/6745464/inverse-cosine-in-python
https://stackoverflow.com/questions/209840/convert-two-lists-into-a-dictionary

<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [5]:
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
Red= [(1,1),(2,1),(4,2),(2,4),(-1,4)]

import re
d_red = []
d_blue= []
final_red = []
final_blue = []
for line in Lines:
    a, b, c = [float(x.strip()) for x in re.split('x|y', line)]
    R = []
    B= []
    for i in range(len(Red)):
        r = ((a*Red[i][0])+(b*Red[i][1])+c)
        R.append(r)
    d_red.append(R)
    for _ in range(len(Blue)):
        z = ((a*Blue[_][0])+ (b*Blue[_][1])+ c)
        B.append(z)
    d_blue.append(B)

final_blue = [all(j < 0 for j in i) for i in d_blue]
final_red = [all(k>0 for k in i) for i in d_red]

for i in range(len(final_blue)):
    if(final_blue[i]==True and final_red[i]==True):
        print("Yes")
    else:
        print('No')

Yes
No
No
Yes


Reference : https://stackoverflow.com/questions/20229822/check-if-all-values-in-list-are-greater-than-a-certain-number
https://stackoverflow.com/questions/57218697/getting-error-float-object-is-not-iterable-when-trying-to-check-if-values-in-t/57219138#57219138

<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [6]:
def blanks(S):
    a = S.split(',')
    count = 0
    middle_store = 0
    # left
    for i in range(len(a)):
        if a[i] == '_':
            count = count + 1  # find number of blanks to the left of a number
        else:
            for j in range(i + 1):
                # if there are n blanks to the left of the number speard the number equal over n+1 spaces
                a[j] = str((float(a[i]) / (count + 1)))
            middle_store = i
            middle_store_value = float(a[i])
            break

        # blanks in the middle
    denominator = 1
    flag = 0
    for k in range(middle_store + 1, len(a)):
        if a[k] != '_':
            denominator = (k + 1 - middle_store)
            flag = k
            break
    flag_value = float(a[flag])
    for p in range(middle_store, flag + 1):
        a[p] = str((middle_store_value+flag_value) / denominator)

    # blanks at the right
    last_value = float(a[flag])
    for q in range(flag, len(a)):
        a[q] = str(last_value / (len(a) - flag))

    return a

S=  "_,_,30,_,_,_,50,_,_"
print(blanks(S))

['10.0', '10.0', '12.0', '12.0', '12.0', '12.0', '4.0', '4.0', '4.0']


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [21]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# you can free to change all these codes/structure

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

dictionary1 = {
 'F1S1':0,
 'F2S1':0,
 'F3S1':0,
 'F4S1':0,
 'F5S1':0,
 'F1S2':0,
 'F2S2':0,
 'F3S2':0,
 'F4S2':0,
 'F5S2':0,
 'F1S3':0,
 'F2S3':0,
 'F3S3':0,
 'F4S3':0,
 'F5S3':0,
}

dictionary2= {
 'S1':0,
 'S2':0,
 'S3':0
}

def compute_conditional_probabilites(A):
    for i in range(len(A)):
        if(A[i][0]=='F1'and A[i][1]=='S1'):
            dictionary1['F1S1'] = dictionary1['F1S1'] +1
            dictionary2['S1'] = dictionary2['S1'] +1
        if(A[i][0]=='F1'and A[i][1]=='S2'):
            dictionary1['F1S2'] = dictionary1['F1S2'] +1
            dictionary2['S2'] = dictionary2['S2'] +1
        if(A[i][0]=='F1'and A[i][1]=='S3'):
            dictionary1['F1S3'] = dictionary1['F1S3'] +1
            dictionary2['S3'] = dictionary2['S3'] +1
        if(A[i][0]=='F2'and A[i][1]=='S1'):
            dictionary1['F2S1'] = dictionary1['F2S1'] +1
            dictionary2['S1'] = dictionary2['S1'] +1
        if(A[i][0]=='F2'and A[i][1]=='S2'):
            dictionary1['F2S2'] = dictionary1['F2S2'] +1
            dictionary2['S2'] = dictionary2['S2'] +1
        if(A[i][0]=='F2'and A[i][1]=='S3'):
            dictionary1['F2S3'] = dictionary1['F2S3'] +1
            dictionary2['S3'] = dictionary2['S3'] +1
        if(A[i][0]=='F3'and A[i][1]=='S1'):
            dictionary1['F3S1'] = dictionary1['F3S1'] +1
            dictionary2['S1'] = dictionary2['S1'] +1
        if(A[i][0]=='F3'and A[i][1]=='S2'):
            dictionary1['F3S2'] = dictionary1['F3S2'] +1
            dictionary2['S2'] = dictionary2['S2'] +1
        if(A[i][0]=='F3'and A[i][1]=='S3'):
            dictionary1['F3S3'] = dictionary1['F3S3'] +1
            dictionary2['S3'] = dictionary2['S3'] +1
        if(A[i][0]=='F4'and A[i][1]=='S1'):
            dictionary1['F4S1'] = dictionary1['F4S1'] +1
            dictionary2['S1'] = dictionary2['S1'] +1
        if(A[i][0]=='F4'and A[i][1]=='S2'):
            dictionary1['F4S2'] = dictionary1['F4S2'] +1
            dictionary2['S2'] = dictionary2['S2'] +1
        if(A[i][0]=='F4'and A[i][1]=='S3'):
            dictionary1['F4S3'] = dictionary1['F4S3'] +1
            dictionary2['S3'] = dictionary2['S3'] +1
        if(A[i][0]=='F5'and A[i][1]=='S1'):
            dictionary1['F5S1'] = dictionary1['F5S1'] +1
            dictionary2['S1'] = dictionary2['S1'] +1
        if(A[i][0]=='F5'and A[i][1]=='S2'):
            dictionary1['F5S2'] = dictionary1['F5S2'] +1
            dictionary2['S2'] = dictionary2['S2'] +1
        if(A[i][0]=='F5'and A[i][1]=='S3'):
            dictionary1['F5S3'] = dictionary1['F5S3'] +1
            dictionary2['S3'] = dictionary2['S3'] +1                                

compute_conditional_probabilites(A)

print('Probability of P(F=F1|S==S1) =',(dictionary1['F1S1']/dictionary2['S1']))
print('Probability of P(F=F1|S==S2) =',(dictionary1['F1S2']/dictionary2['S2']))
print('Probability of P(F=F1|S==S3) =',(dictionary1['F1S3']/dictionary2['S3']))
print('Probability of P(F=F2|S==S1) =',(dictionary1['F2S1']/dictionary2['S1']))
print('Probability of P(F=F2|S==S2) =',(dictionary1['F2S2']/dictionary2['S2']))
print('Probability of P(F=F2|S==S3) =',(dictionary1['F2S3']/dictionary2['S3']))
print('Probability of P(F=F3|S==S1) =',(dictionary1['F3S1']/dictionary2['S1']))
print('Probability of P(F=F3|S==S2) =',(dictionary1['F3S2']/dictionary2['S2']))
print('Probability of P(F=F3|S==S3) =',(dictionary1['F3S3']/dictionary2['S3']))
print('Probability of P(F=F4|S==S1) =',(dictionary1['F4S1']/dictionary2['S1']))
print('Probability of P(F=F4|S==S2) =',(dictionary1['F4S2']/dictionary2['S2']))
print('Probability of P(F=F4|S==S3) =',(dictionary1['F4S3']/dictionary2['S3']))
print('Probability of P(F=F5|S==S1) =',(dictionary1['F5S1']/dictionary2['S1']))
print('Probability of P(F=F5|S==S2) =',(dictionary1['F5S2']/dictionary2['S2']))
print('Probability of P(F=F5|S==S3) =',(dictionary1['F5S3']/dictionary2['S3']))

Probability of P(F=F1|S==S1) = 0.25
Probability of P(F=F1|S==S2) = 0.3333333333333333
Probability of P(F=F1|S==S3) = 0.0
Probability of P(F=F2|S==S1) = 0.25
Probability of P(F=F2|S==S2) = 0.3333333333333333
Probability of P(F=F2|S==S3) = 0.3333333333333333
Probability of P(F=F3|S==S1) = 0.0
Probability of P(F=F3|S==S2) = 0.3333333333333333
Probability of P(F=F3|S==S3) = 0.3333333333333333
Probability of P(F=F4|S==S1) = 0.25
Probability of P(F=F4|S==S2) = 0.0
Probability of P(F=F4|S==S3) = 0.3333333333333333
Probability of P(F=F5|S==S1) = 0.25
Probability of P(F=F5|S==S2) = 0.0
Probability of P(F=F5|S==S3) = 0.0


<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [13]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# you can free to change all these codes/structure
def string_features(S1, S2):
    a=[]
    b=[]
    c=[]
    for ch in S1.split():
        for ch1 in S2.split():
            if(ch ==ch1):
                a.append(ch)
    print(len(a))
    b= list(set(S1.split())-set(S2.split()))
    print(b)
    c = list(set(S2.split())-set(S1.split()))
    print(c)

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
print(string_features(S1, S2))

7
['5', 'F', 'first']
['3', 'second', 'S']
None


Reference:
https://stackoverflow.com/questions/11938964/how-to-find-common-words-and-print-them-using-python-command
https://www.geeksforgeeks.org/python-difference-two-lists/

<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [11]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

import math

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]

def compute_log_loss(A):
    sum = 0
    for i in range(len(A)):
        sum = sum + ((A[i][0] * math.log(A[i][1],10)) + ((1-A[i][0]) * (math.log(1-A[i][1],10))))
    return sum 

print((compute_log_loss(A)/8)*(-1))



0.42430993457031635
